name: xkesval/waka-readme-stats
on:
  schedule: [{ cron: "0 8 * * *" }]
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: 🍕 WakaReadme-Stats
        uses: anmol098/waka-readme-stats@master
        with:
          config_timezone: Asia/Taipei
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: "TRUE"
          SHOW_DAYS_OF_WEEK: "TRUE"
          SHOW_LANGUAGE: "TRUE"
          SHOW_OS: "TRUE"
          SHOW_EDITORS: "FALSE"
          SHOW_TIMEZONE: "FALSE"
          SHOW_LANGUAGE_PER_REPO: "FALSE"
          SHOW_TOTAL_CODE_TIME: "TRUE"
          SHOW_UPDATED_DATE: "FALSE"
          SHOW_PROJECTS: "FALSE"
          SHOW_PROFILE_VIEWS: "FALSE"
          SHOW_SHORT_INFO: "FALSE"
          SHOW_LOC_CHART: "FALSE"
          SYMBOL_VERSION: 3
